### ISSUE TITLE
gameモデルのテストでの問題

### ISSUE THREAD

**Issue by uchiyu** [SLP-KBIT/AppLoader#38]
gameのdl_countの生成をランダムで行っているが、値によってテストが通らない場合がある。
そこでdl_countの生成において、特定の数値を格納した配列を用いた方が良いのではないのか。
また、現在テストに通らない原因の特定を行う必要がある。

**Comment by vitamiena** [comment]
対応1 : Gameのfactory_girlからランダム要素を排除
対応2 : Game#dl_topとGame#new_topの整列の第2引数に「タイトル」を利用
対応3 : top_controllerのspecで、Gameのメソッドのテストをしていたのを削除
            top_controller => ロードできているかのテストのみ
対応4 : Gameのメソッドテストをリファクタリング
